### ISSUE TITLE
不兼容laravel8

### ISSUE THREAD

**Issue by north521** [yangjisen/LaravelCacheProvider#3]
Problem 1
    - Root composer.json requires yangjisen/laravel-cache-provider ^3.0 -> satisfiable by yangjisen/laravel-cache-provider[v3.0.0].
    - yangjisen/laravel-cache-provider v3.0.0 requires laravel/framework ^5.1||^6.0||^7.0 -> found laravel/framework[v5.1.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ...,
7.x-dev] but it conflicts with your root composer.json require (^8.0).

**Comment by yangjisen** [comment]
提供您当前使用的版本 或者 修改 composer.json
```
"require-dev": {
        "yangjisen/laravel-cache-provider": "^3.0"
}
```

**Comment by north521** [comment]
> 提供您当前使用的版本或修改composer.json
> 
> ```
> "require-dev": {
>         "yangjisen/laravel-cache-provider": "^3.0"
> }
> ```

包最新版本3.0，   laravel8最新版本
