### ISSUE TITLE
不支持多模型吗？

### ISSUE THREAD

**Issue by waney** [yangjisen/LaravelCacheProvider#4]
![image](https://user-images.githubusercontent.com/69211/185776338-7df30fb9-138b-442e-8bf8-94c2a65f6376.png)

![image](https://user-images.githubusercontent.com/69211/185776343-36699d21-982b-48f1-a738-d5098174238a.png)

**Comment by waney** [comment]
抱歉，可能弄错了，应该是Passport OAuth  多guards的问题。

**Comment by yangjisen** [comment]
OK
